spring.application.name=TaskManager
# MySQL# Database Configuration (Temporary disabled for testing)
 spring.datasource.url=jdbc:mysql://localhost:3306/TaskManagerDb
 spring.datasource.username=root
 spring.datasource.password=Fuad2006
 spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration (Temporary disabled)
 spring.jpa.hibernate.ddl-auto=update
 spring.jpa.show-sql=true
 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# H2 In-Memory Database for testing
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.mvc.locale=en_US
spring.mvc.locale-resolver=fixed

# Mail server configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sevxanli77@gmail.com
spring.mail.password=kadf dvcq digj muuf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
security.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970